name = "QuasiMonteCarlo"
uuid = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
authors = ["ludoro <ludovicobessi@gmail.com>, Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.3.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LatticeRules = "73f95e8e-ec14-4e6a-8b18-0d2e271c4e55"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extensions]
QuasiMonteCarloDistributionsExt = "Distributions"

[compat]
Accessors = "0.1"
ConcreteStructs = "0.2"
Distributions = "0.25"
LatticeRules = "0.0.1"
LinearAlgebra = "1.9"
Primes = "0.5"
Random = "1.9"
Sobol = "1.5"
julia = "1.9"
